<select name='attr[shoe_size]' name="foot_size">  
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
		<option value="British 5">British 5</option>
		<option value="British 5.5">British 5.5</option>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
        <option value="British 6">British 6</option>
		<option value="British 6.5">British 6.5</option>
        <option value="British 7">British 7</option>
        <option value="British 7.5">British 7.5</option>
        <option value="British 8">British 8</option>
        <option value="British 8.5">British 8.5</option>
        <option value="British 9">British 9</option>
        <option value="British 9.5">British 9.5</option>
        <option value="British 10">British 10</option>
        <option value="British 10.5">British 10.5</option>
        <option value="British 11">British 11</option>
        <option value="British 11.5">British 11.5</option>
        <option value="British 12">British 12</option>
        

</select>