<select name='attr[shoe_size]' name="foot_size">  
		<option value="Euro 34">Euro 34</option>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
		<option value="Euro 34.5">Euro 34.5</option>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
		<option value="Euro 35">Euro 35</option>
		<option value="Euro 35.5">Euro 35.5</option>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
        <option value="Euro 36">Euro 36</option>
		<option value="Euro 36.5">Euro 36.5</option>
        <option value="Euro 37">Euro 37</option>
        <option value="Euro 37.5">Euro 37.5</option>
        <option value="Euro 38">Euro 38</option>
        <option value="Euro 38.5">Euro 38.5</option>
		<option value="Euro 39">Euro 39</option>
        <option value="Euro 39.5">Euro 39.5</option>
        <option value="Euro 40">Euro 40</option>
</select>