<select name='attr[shoe_size]' name="foot_size">                                 
		<option value="American Standard 5">American Standard 5</option>
		<option value="American Standard 5.5">American Standard 5.5</option>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
        <option value="American Standard 6">American Standard 6</option>
		<option value="American Standard 6.5">American Standard 6.5</option>
        <option value="American Standard 7">American Standard 7</option>
        <option value="American Standard 7.5">American Standard 7.5</option>
        <option value="American Standard 8">American Standard 8</option>
        <option value="American Standard 8.5">American Standard 8.5</option>
        <option value="American Standard 9">American Standard 9</option>
        <option value="American Standard 9.5">American Standard 9.5</option>
        <option value="American Standard 10">American Standard 10</option>
        
</select>