<select name='attr[shoe_size]' name="foot_size">                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
        <option value="American Standard 6">American Standard 6</option>
		<option value="American Standard 6.5">American Standard 6.5</option>
        <option value="American Standard 7">American Standard 7</option>
        <option value="American Standard 7.5">American Standard 7.5</option>
        <option value="American Standard 8">American Standard 8</option>
        <option value="American Standard 8.5">American Standard 8.5</option>
        <option value="American Standard 9">American Standard 9</option>
        <option value="American Standard 9.5">American Standard 9.5</option>
        <option value="American Standard 10">American Standard 10</option>
        <option value="American Standard 10.5">American Standard 10.5</option>
        <option value="American Standard 11">American Standard 11</option>
        <option value="American Standard 11.5">American Standard 11.5</option>
        <option value="American Standard 12">American Standard 12</option>
        <option value="American Standard 12.5">American Standard 12.5</option>
        <option value="American Standard 13">American Standard 13</option>
</select>