<?php

class Application_Constants_Category
{
	static public $CATEGORY = array('MEN' => array(
										'Men Dance Pants' 		=> array('brands'		=> array('VEdance'	=> array('VE Classic'=> 155
																													 //,'VE Executive'=>135
																													 )),
																	 'banner_image' => 'VEproductpic.png'),
										'Men Vests' 	  		=> array('VEdance'	=> array('VE Classic Vest'=>145, 'VE Executive Vest'=>145)),
										'Men Sets'		 		=> array('VEdance'		=> array('VE Classic Set'=>265, 'VE Executive Vest'=>265)), 
										'Men Standard Dance Shoes'	=> array('brands'  		=> array('Stephanie Professional' 	=> array('94001' => 115,
																								 		 						 	 '96008' => 115,
																								 		 						 	 '96010' => 115),
															   		 						 	'Rayrose Dance Shoes' 		=> array('Sandstorm'=> 155, 
																																 	 'Windrush' => 155),
															   		 						 	'Dance Naturals'			=> array('Art 11'   => 210, 
																								 	 	 						 	 'Art 117 Dance Flex' => 210,
																								 		 						 	 'Art 127 Dance Flex' => 210)),
																	 	 'banner_image' => 'Men dance shoes banner.jpg'),
										'Men Latin Dance Shoes'		=> array('brands'  		=> array('Stephanie Professional' 	=> array('93001' => 115),
															   		 						 	'Rayrose Dance Shoes' 		=> array('Bryan' 	=> 170, 
																																 	 'Thunder'  => 155),
															   		 						 	'Dance Naturals'			=> array('Art 10' 	=> 210,
																								 		 						 	 'Art 116 Dance Flex' => 210,
																								 		 						 	 'Art 116 50' => 210,
																								 		 						 	 'Art 126' => 210)),
																	 	 'banner_image' => 'Men dance shoes banner.jpg')),				
									'WOMEN'	=> array(
										'Women Skirts'			=> array('VEdance' 		=> array('B23', 'B24', 'B25', 'B26')),
										'Women Closed Toe Shoes'=> array('brands' 	=> array(
																							 'Rayrose Dance Shoes' 		=> array('Savannah'	 => 155,
																																 'Sirocco'	 => 145,
																																 'Bora'		 => 145,
																																 'Ion'		 => 145,
																																 'Stratus' 	 => 145,
																																 'Landslide' => 145,
																																 'Nimbus'	 => 145,
																																 'Rockslide' => 145),
																							 'Dance Naturals'			=> array('Art 220'	 => 205,
																																 'Art 223' 	 => 205,
																																 'Art 28 Diva' => 205,
																																 'Art 29 Diva' => 195,
																																 'Art 400 Perla' => 195,
																																 'Art 901 Sinderella' => 285),
																							 'Stephanie Professional' 	=> array('stp 95001' => 105,
																																 'stp 95004' => 105))),
										'Women Open Toe Shoes' 	=> array('brands'	=> array(
																	 						 'Rayrose Dance Shoes'	  	=> array('Amazon'	 => 150,
																																 'Blizzard'  => 145,
																	 						 									 'Carmen' 	 => 170, 
																																 'Carmen 3'	 => 170,
																																 'Cirrus'	 => 145,
																																 'Cloudburst'=> 145,
																																 'Drizzle'	 => 145,
																																 'Drizzle Metalic' => 175,
																																 'Gobi'		 => 145,
																																 'Kalahari'	 => 150,
																																 'Meteor'	 => 145,
																																 'Mojave'	 => 145,
																																 'Monsoon' 	 => 145,
																																 'Moonglow'	 => 145,
																																 'Snow Flake'=> 145,
																																 'Sahara' 	 => 145,
																																 'T Atlas'	 => 145,
																																 'Tropic'	 => 145),
																							'Stephanie Professional' 	=> array('stp 92001' => 110, 
																																 'stp 92005' => 115,
																																 'stp 92006' => 115,
																																 'stp 92008' => 115,
																																 'stp 92011' => 115,
																																 'stp 92015' => 115),
																	 						 'Dance Naturals'		  	=> array('Art 201' => 210,
																									     						 'Art 202' => 210,
																																 'Art 203' => 210,
																																 'Art 204' => 210,
																																 'Art 205' => 210,
																																 'Art 306 Dafine' => 210,
														 																		 'Art 406 Perla'  => 210,
																																 'Art 409 Perla'  => 210,
																																 'Art 506 Stella' => 210,
																																 'Art 509 Stella' => 210,
																																 'Art 27 Diva' 	  => 199,
																																 'Art 884 Simple Venere' => 249,
																																 'Art 883 Venere' => 299,
																																 'Art 886 Venere' => 299,
																									     						 'Dance Boots Art 070' => 360, 
																									   	 						 'Dance Boots Art 007' => 395)),
																		'banner_image' => '')
													),

										'PACKAGES' => array(
													'Mens Dance Packages' => array('brands' => array('Betty' 	=> array('Mens Bronze Package' => 230,
																													 	 'Mens Silver Package' => 305,
																													 	 'Mens Gold Package'   => 440,
																														 'Mens Platinum Package' => 565,))),
													'Womens Dance Packages' => array('brands' => array('Betty' 	=> array('Womens Bronze Standard Package' => 158.50,
																														 'Womens Bronze Latin  Package'	  => 140.50,
																														 'Womens Silver Standard Package' => 213.50,
																														 'Womens Silver Latin  Package'    => 195.50,
																														 'Womens Gold Pakcage'			  => 281.00,))),
													'Bronze Packages' 	=> array('brands' => array('Betty' 	=> array('Mens Bronze Package' => 230,))),
													'Silver Packages' 	=> array('brands' => array('Betty' 	=> array('Mens Silver Package' => 305,))),
													'Gold Packages' 	=> array('brands' => array('Betty' 	=> array('Mens Gold Package' => 440,))),
													
													
													),
									);
															
	static public $ITEM_IMAGES = array('VE Classic' => array('VE Classic', 'VE Classic sample', 'VE Classic side'),
									   //Men's Standard Shoes professional
									   '94001' 		=> array('94001', '94001 leather', '94001 patent'),
									   '96008' 		=> array('96008'),
									   '96010' 		=> array('96010'),
									   //Men's Standard Rayrose professional
									   'Sandstorm'	=> array('Sandstorm', 'Sandstorm side', 'Sandstorm leather', 'Sandstorm leather side'),
									   'Windrush'	=> array('Windrush', 'Windrush leather', 'Windrush patent side', 'Windrush leather side'),
									   //Men's Dance Naturals
									   'Art 11'		=> array('Art 11', 'Art 11 patent'),
									   'Art 117 Dance Flex' => array('Art 117 Dance Flex', 'Art 117 Dance Flex patent', 'Art 117 brown', 'Art 117 Heel', 'Art 117 Sole'),
									   'Art 127 Dance Flex' => array('Art 127 Dance Flex', 'Art 127 Dance Flex brown'),
									   //Men's Latin stephanie professional
									   '93001' 		=> array('93001'),
									   'Bryan'		=> array('Bryan', 'Bryan Watson', 'Bryan side', 'Bryan patent', 'Bryan patent side', 'Bryan heel'),
									   'Thunder' 	=> array('Thunder', 'Thunder white', 'Thunder white side', 'Thunder trouser', 'Thunder side'),
									   'Art 10'		=> array('Art 10', 'Art 10 narbuk', 'Art 10 leather'),
									   'Art 116 50' => array('Art 116 50', 'Art 116 50 narbuk', 'Art 116 50 heel'),
									   'Art 116 Dance Flex' => array('Art 116 Dance Flex', 'Art 116 Narbuk', 'Art 116 Dance Flex brown', 'Art 116 brown sole', 'Art 116 heel'),
									   'Art 126'	=> array('Art 126', 'Art 126 Brown'),								   
									   //Stephanie Professional Standard Shoes
									   'stp 95001' 	=> array('stp 95001'),
									   'stp 95004'  => array('stp 95004'),
									   //Rayrose Standard Shoes
									   'Bora'		=> array('107_bora_flesh', '107_flesh_binding', '107_flesh_front', '107_flesh_side','107_bora_white', '107_white_front', '107_white_side'),
									   'Ion'		=> array('108_ion_flesh'),
									   'Landslide'  => array('Landslide','Landslide tan side', 'Landslide toe', 'Landslide white'),
									   'Nimbus' 	=> array('119_nimbus_flesh', '119_nimbus_flesh_side', '119_nimbus_white', '119_white_front', '119_white_side'),
									   'Rockslide'	=> array('Rockslide', 'Rockslide top', 'Rockslide side', '116_rockslide_light_tan', '116_rockslide_lightflesh_side', '116_rockslide_lightflesh_top', 'Rockslide white', 'Rockslide white side'),
									   'Savannah'	=> array('129_savannah_flesh', '129_savannah_flesh_top', '129_savannah_flesh_side', '129_savannah_flesh_trim'),
									   'Sirocco' 	=> array('103_sirocco_flesh', '103_flesh_side', '103_flesh_front'),
									   'Stratus' 	=> array('117_stratus_flesh'),
									   //Dance Naturals Standard Shoes
									   'Art 28 Diva'=> array('Art 28 Diva', 'Art 28 Diva black'),
									   'Art 29 Diva'=> array('Art 29 Diva', 'Art 29 Diva black'),
									   'Art 220'	=> array('Art 220', 'Art 220 top', 'Art 220 heels', 'Art 220 heel'),
									   'Art 223'	=> array('Art 223', 'Art 223 black', 'Art 223 white'),
									   'Art 400 Perla' => array('Art 400 Perla', 'Art 400 Perla top', 'Art 400 Perla heel'),
									   'Art 901 Sinderella' => array('Art 901 Sinderella', 'Art 901 Sinderella white'),
									   //Stephanie Professional Latin Shoes
									   'stp 92001'	=> array('stp 92001', 'stp 92001 lightflesh'),
									   'stp 92005' 	=> array('stp 92005', 'stp 92005 lighttan', 'stp 92005 black'),
									   'stp 92006'	=> array('stp 92006', 'stp 92006 black'),
									   'stp 92008'	=> array('stp 92008', 'stp 92008 black'),
									   'stp 92011'  => array('stp 92011', 'stp 92011 black'),
									   'stp 92015'	=> array('stp 92015', 'stp 92015 darktan', 'stp 92015 black'),
									   //Rayrose Latin Shoes
									   'Amazon'		=> array('Amazon', '879_amazon_darktan_side','879_amazon_darktan_top'),
									   'Blizzard'	=> array('Blizzard', '820_darktan_side', '820_darktan_front', '820_blizzard_black', '820_black_side', '820_black_front', '820_blizzard_white', '820_white_side', '820_white_front'),
									   'Carmen'		=> array('Carmen', 'C111_mocha_side','C111_mocha_front', 'C111_mocha_back', 'C111_carmen_newflesh', 'C111_newflesh_side', 'C111_newflesh_front','C111_newflesh_back'),
									   'Carmen 3' 	=> array('Carmen 3'),
									   'Cirrus'		=> array('Cirrus'),
									   'Cloudburst' => array('Cloudburst'),
									   'Drizzle'	=> array('Drizzle', '825_darktan_side', '825_darktan_front', '825_drizzle_flesh', '825_newflesh_side', '825_newflesh_front'),
									   'Drizzle Metalic' => array('Drizzle Metalic', '825_gold_heel', '825_drizzle_black_silver', '825_black_silver_side','825_black_silver_front'),
									   'Gobi' 		=> array('Gobi', '840_darktan_side', '840_darktan_front', '840_cyclone_black', '840_black_side',  '840_black_front'),
									   'Kalahari' 	=> array('Kalahari', '860_darktan_side', '860_darktan_front', '860_earthquake_black', '860_black_side', '860_black_front'),
									   'Meteor' 	=> array('Meteor', '890_darktan_side', '890_darktan_front'),
									   'Mojave' 	=> array('Mojave', '870_darktan_side', '870_darktan_front'),
									   'Monsoon'	=> array('Monsoon', '835_darktan_side', '835_darktan_front'),
									   'Moonglow'	=> array('Moonglow', '869_moonglow_darktan_side', '869_moonglow_darktan_top'),
									   'Sahara'		=> array('Sahara', '809_darktan_side', '809_darktan_front'),
									   'Snow Flake'	=> array('Snow Flake', '812_darktan_side', '812_darktan_front', '812_snowflake_black', '812_black_side', '812_black_front'),
									   'T Atlas'	=> array('T Atlas', '860T_atlas_newflesh_side', '860T_atlas_newflesh_top'),
									   'Tropic'		=> array('Tropic', '889_tropic_darktan_side', '889_tropic_darktan_top'),
									   //Dance Naturals Latin Shoes
									   'Art 27 Diva'=> array('Art 27 Diva'),
									   'Art 201'	=> array('Art 201', 'Art 201 black', 'Art 201 heel', 'Art 201 top'),
									   'Art 202'	=> array('Art 202', 'Art 202 black', 'Art 202 heel', 'Art 202 toe'),
									   'Art 203'	=> array('Art 203', 'Art 203 black', 'Art 203 heel', 'Art 203 toe'),
									   'Art 204'	=> array('Art 204', 'Art 204 black', 'Art 204 heel', 'art 204 toe'),
									   'Art 205'	=> array('Art 205', 'Art 205 black', 'Art 205 heel', 'Art 205 toe'),
									   'Art 306 Dafine' => array('Art 306 Dafine', 'Art 306 black', 'Art 306 heel', 'Art 306 toe'),
									   'Art 406 Perla'  => array('Art 406 Perla'),
									   'Art 409 Perla'  => array('Art 409 Perla heel', 'Art 409 Perla toe'),
									   'Art 506 Stella' => array('Art 506 Stella', 'Art 506 Stella black'),
									   'Art 509 Stella' => array('Art 509 Stella', 'Art 509 Stella black', 'Art 509 heel', 'Art 509 toe'),
									   'Art 883 Venere' => array('Art 883 Venere', 'Art 883 Venere Black', 'Art 883 Venere Silver Leather', 'Art 883 Venere Black Silver', 'Art 883 Venere heels', 'Art 883 Venere pair', 'Art 883 Venere Toe'),
									   'Art 884 Simple Venere' => array('Art 884 Simple Venere', 'Art 884 Simple Venere black', 'Art 884 Simple Venere silver', 'Art 884 Simple Venere heel', 'Art 884 Simple Venere toe'),
									   'Art 886 Venere' => array('Art 886 Venere', 'Art 886 Venere black', 'Art 886 Venere congo', 'Art 886 Venere gold jane', 'Art 886 Venere jane', 'Art 886 heel', 'Art 886 toe'),
									   'Art 887 Simple Venere' => array('Art 887 Simple Venere', 'Art 887 Simple Venere black', 'Art 887 Simple Venere black suede', 'Art 887 Simple Venere congo', 'Art 887 Simple Venere gold jane','Art 887 Simple Venere heel', 'Art 887 Simple Venere toe'),
									   'Dance Boots Art 007'   => array('Dance Boots Art 007', 'Dance Boots Art 007 silver', 'Dance Boots Art 007 gold heel', 'Dance Boots Art 007 bronze heel'),
									   'Dance Boots Art 070'   => array('Dance Boots Art 070', 'Dance Boots Art 070 heel'),
									   'Art 883 Venere'	=> array('Art 883 Venere', 'Art 883 Venere Silver Leather', 'Art 883 Venere Black', 'Art 883 Venere Black Silver', 'Art 883 Venere Toe', 'Art 883 Venere pair', 'Art 883 Venere heels'),
									   'Mens Bronze Package' => array('Mens Bronze Package', '309', '424', 'Shoe brush', 'VE Classic side'),
									   'Mens Silver Package' => array('Mens Silver Package', '309', '424', 'Shoe brush', 'VE Classic side'),
	
	);
	
	
	static public $CATEGORY_FORM_ATTRIBUTES = array('VE Classic' 	=> array('Waist'=> '_waist.tpl'),
													'VE Executive' 	=> array('Waist' => '_waist.tpl'),
													//men shoes
													'94001'			=> array('US Size'  => '_stp_men_shoe_size_6_13.tpl', 'Color' => '_94001_color_selection.tpl'),
													'96008'			=> array('US Size'	=> '_stp_men_shoe_size_6_13.tpl', 'Color' => '_96008_color_selection.tpl'),
													'96010'			=> array('US Size'	=> '_stp_men_shoe_size_6_13.tpl', 'Color' => '_96010_color_selection.tpl'),
													'93001'			=> array('US Size'	=> '_stp_men_shoe_size_6_13.tpl', 'Color' => '_93001_color_selection.tpl'),
													'Sandstorm'		=> array('BR size'  => '_br_men_shoe_size_5_12.tpl',   'Color' => '_Sandstorm_color_selection.tpl'),
													'Windrush'		=> array('BR size' 	=> '_br_men_shoe_size_5_12.tpl',   'Color' => '_Windrush_color_selection.tpl'),
													'Bryan'			=> array('BR size' 	=> '_br_men_shoe_size_5_12.tpl',   'Color' => '_Bryan_color_selection.tpl'),
													'Thunder'		=> array('BR size' 	=> '_br_men_shoe_size_5_12.tpl',   'Color' => '_Thunder_color_selection.tpl'),
													'Art 11' 		=> array('EU size'  => '_DN_men_shoe_size.tpl', 	  'Color' => '_Art_11_color_selection.tpl'),
													'Art 117 Dance Flex' => array('EU Size'  => '_eu_men_shoe_size_37_44.tpl', 'Color' => '_Art_117_Dance_Flex_color_selection.tpl'),
													'Art 127 Dance Flex' => array('EU Size'  => '_eu_men_shoe_size_37_44.tpl', 'Color' => '_Art_127_color_selection.tpl'),
													'Art 10'		=> array('EU Size'  => '_eu_men_shoe_size_37_44.tpl', 'Color' => '_Art_10_color_selection.tpl'),
													'Art 116 50'	=> array('EU Size'  => '_eu_men_shoe_size_37_44.tpl', 'Color' => '_Art_116_50_color_selection.tpl'),
													'Art 116 Dance Flex' => array('EU Size'  => '_eu_men_shoe_size_37_44.tpl', 'Color' => '_Art_116_color_selection.tpl'),
													'Art 126'		=> array('EU Size'  => '_eu_men_shoe_size_37_44.tpl', 'Color' => '_Art_126_color_selection.tpl'),
													//Stephanie Professional Standard Shoes
													'stp 95001' 	=> array('US Size' 	=> '_stp_women_shoe_size_5.tpl', 'Color' => '_95001_color_selection.tpl', 'Heel' => '_us_women_standard_heels.tpl'),
													'stp 95004'		=> array('US Size'	=> '_stp_women_shoe_size_4_5.tpl', 'Color' => '_95004_color_selection.tpl', 'Heel' => '_us_women_standard_heels.tpl'),
													//Rayrose Standard Shoes
													'Bora'			=> array('BR Size'	=> '_br_women_shoe_size_2_8.tpl', 'Color' => '_Bora_color_selection.tpl', 'Heel' => '_br_women_standard_heels.tpl'),
													'Ion'			=> array('BR Size'	=> '_br_women_shoe_size_2_8.tpl', 'Color' => '_Ion_color_selection.tpl', 'Heel' => '_br_women_standard_heels.tpl'),
													'Landslide'		=> array('Br Size'	=> '_br_women_shoe_size_2_8.tpl', 'Color' => '_Landslide_color_selection.tpl', 'Heel' => '_br_women_standard_heels.tpl'),
													'Nimbus'		=> array('Br Size' 	=> '_br_women_shoe_size_2_8.tpl', 'Color' => '_Nimbus_color_selection.tpl', 'Heel'	=> '_br_women_standard_heels.tpl'),
													'Rockslide'		=> array('Br Size' 	=> '_br_women_shoe_size_2_8.tpl', 'Color' => '_Rockslide_color_selection.tpl', 'Heel'	=> '_br_women_standard_heels.tpl'),
													'Savannah'		=> array('Br Size' 	=> '_br_women_shoe_size_2_8.tpl', 'Color' => '_Savannah_color_selection.tpl', 'Heel'	=> '_br_women_standard_heels.tpl'),
													'Sirocco'		=> array('Br Size' 	=> '_br_women_shoe_size_2_8.tpl', 'Color' => '_Sirocco_color_selection.tpl', 'Heel'	=> '_br_women_standard_heels.tpl'),
													'Stratus'		=> array('Br Size' 	=> '_br_women_shoe_size_2_8.tpl', 'Color' => '_Stratus_color_selection.tpl', 'Heel'	=> '_br_women_standard_heels.tpl'),
													//Dance Naturals Standard Shoes
													'Art 28 Diva'	=> array('EU Size'	=> '_eu_women_shoe_size_34_40.tpl', 'Color' => '_Art_28_Diva_color_selection.tpl', 'Heel' => '_DN_women_standard_heels.tpl'),
													'Art 29 Diva'	=> array('EU Size'	=> '_eu_women_shoe_size_34_40.tpl', 'Color' => '_Art_29_Diva_color_selection.tpl', 'Heel' => '_DN_women_standard_heels.tpl'),
													'Art 220'		=> array('EU Size'	=> '_eu_women_shoe_size_34_40.tpl', 	'Color' => '_Art_220_color_selection.tpl', 'Heel' => '_DN_women_standard_heels.tpl'),
													'Art 223'		=> array('EU Size'	=> '_eu_women_shoe_size_34_40.tpl', 	'Color' => '_Art_223_color_selection.tpl', 'Heel' => '_DN_women_standard_heels.tpl'),
													'Art 400 Perla'	=> array('EU Size'	=> '_eu_women_shoe_size_34_40.tpl', 'Color' => '_Art_400_Perla_color_selection.tpl', 'Heel' => '_DN_women_standard_heels.tpl'),
													'Art 901 Sinderella'=> array('EU Size'	=> '_eu_women_shoe_size_34_40.tpl', 'Color' => '_Art_901_Sinderella_color_selection.tpl', 'Heel' => '_DN_women_900_heels.tpl'),
													//Stephanie Professional Latin Shoes	
													'stp 92001'		=> array('US Size'	=> '_stp_women_shoe_size_4_5.tpl', 'Color'=>'_92001_color_selection.tpl', 'Heel' => '_us_women_latin_heels.tpl'),
													'stp 92005'		=> array('US Size'	=> '_stp_women_shoe_size_4_5.tpl', 'Color'=>'_92005_color_selection.tpl', 'Heel' => '_us_women_latin_heels.tpl'),	
													'stp 92006'		=> array('US Size'	=> '_stp_women_shoe_size_4_5.tpl', 'Color'=>'_92006_color_selection.tpl', 'Heel' => '_us_women_latin_heels.tpl'),	
													'stp 92008'		=> array('US Size'	=> '_stp_women_shoe_size_4_5.tpl', 'Color'=>'_92008_color_selection.tpl', 'Heel' => '_us_women_latin_heels.tpl'),	
													'stp 92011'		=> array('US Size'	=> '_stp_women_shoe_size_4_5.tpl', 'Color'=>'_92011_color_selection.tpl', 'Heel' => '_us_women_latin_heels.tpl'),	
													'stp 92015'		=> array('US Size'	=> '_stp_women_shoe_size_4_5.tpl', 'Color'=>'_92015_color_selection.tpl', 'Heel' => '_us_women_latin_heels.tpl'),
													//Rayrose Latin Shoes
													'Amazon'		=> array('Br Size'  => '_br_women_shoe_size_1_8.tpl', 'Color' => '_Amazon_color_selection.tpl', 'Heel' => '_br_women_latin_heels.tpl'),
													'Blizzard'		=> array('Br Size'  => '_br_women_shoe_size_1_8.tpl', 'Color' => '_Blizzard_color_selection.tpl', 'Heel' => '_br_women_latin_heels.tpl'),
													'Carmen'		=> array('Br Size'  => '_br_women_shoe_size_2_8.tpl', 'Color' => '_Carmen_color_selection.tpl', 'Heel' => '_br_women_latin_heels_2-5_3.tpl'),
													'Carmen 3'		=> array('Br Size'  => '_br_women_shoe_size_2_8.tpl', 'Color' => '_Carmen_3_color_selection.tpl', 'Heel' => '_br_women_latin_heels_2-5_3.tpl'),
													'Cirrus'		=> array('Br Size'  => '_br_women_shoe_size_2_8.tpl', 'Color' => '_Cirrus_color_selection.tpl', 'Heel' => '_br_women_latin_heels_2-5_3.tpl'),
													'Cloudburst'	=> array('Br Size'  => '_br_women_shoe_size_2_8.tpl', 'Color' => '_Cloudburst_color_selection.tpl', 'Heel' => '_br_women_latin_heels_2-5_3.tpl'),
													'Drizzle'		=> array('Br Size'  => '_br_women_shoe_size_2_8.tpl', 'Color' => '_Drizzle_color_selection.tpl', 'Heel' => '_br_women_latin_heels_2-5_3.tpl'),
													'Drizzle Metalic'	=> array('Br Size'  => '_br_women_shoe_size_2_8.tpl', 'Color' => '_Drizzle_Metalic_color_selection.tpl', 'Heel' => '_br_drizzle_metalic_heels.tpl'),
													'Gobi'			=> array('Br Size'  => '_br_women_shoe_size_2_8.tpl', 'Color' => '_Gobi_color_selection.tpl', 'Heel' => '_br_women_latin_heels_2-5_3.tpl'),
													'Kalahari'		=> array('Br Size'  => '_br_women_shoe_size_2_8.tpl', 'Color' => '_Kalahari_color_selection.tpl', 'Heel' => '_br_women_latin_heels_2-5_3.tpl'),
													'Meteor'		=> array('Br Size'  => '_br_women_shoe_size_2_8.tpl', 'Color' => '_Meteor_color_selection.tpl', 'Heel' => '_br_women_latin_heels_2-5_3.tpl'),
													'Mojave'		=> array('Br Size'  => '_br_women_shoe_size_2_8.tpl', 'Color' => '_Mojave_color_selection.tpl', 'Heel' => '_br_women_latin_heels_2-5_3.tpl'),
													'Monsoon'		=> array('Br Size'  => '_br_women_shoe_size_2_8.tpl', 'Color' => '_Monsoon_color_selection.tpl', 'Heel' => '_br_women_latin_heels_2-5_3.tpl'),
													'Moonglow'		=> array('Br Size'  => '_br_women_shoe_size_2_8.tpl', 'Color' => '_Moonglow_color_selection.tpl', 'Heel' => '_br_women_latin_heels_2-5_3.tpl'),
													'Sahara'		=> array('Br Size'  => '_br_women_shoe_size_2_8.tpl', 'Color' => '_Sahara_color_selection.tpl', 'Heel' => '_br_women_latin_heels_2-5_3.tpl'),
													'Snow Flake'	=> array('Br Size'  => '_br_women_shoe_size_2_8.tpl', 'Color' => '_Snow_Flake_color_selection.tpl', 'Heel' => '_br_women_latin_heels_2-5_3.tpl'),
													'T Atlas'		=> array('Br Size'  => '_br_women_shoe_size_2_8.tpl', 'Color' => '_T_Atlas_color_selection.tpl', 'Heel' => '_br_women_latin_heels_2-5_3.tpl'),
													'Tropic'		=> array('Br Size'  => '_br_women_shoe_size_2_8.tpl', 'Color' => '_Tropic_color_selection.tpl', 'Heel' => '_br_women_latin_heels_2-5_3.tpl'),	
													//Dance Naturals Latin Shoes
													'Art 27 Diva' 	=> array('EU Size' 	=> '_eu_women_shoe_size_34_40.tpl', 'Color' => '_Art_27_Diva_color_selection.tpl', 'Heel' => '_DN_latin_heels.tpl'),
													'Art 201' 		=> array('EU Size' 	=> '_eu_women_shoe_size_34_40.tpl', 'Color' => '_Art_201_color_selection.tpl', 'Heel' => '_Art_201_heels.tpl'),
													'Art 202' 		=> array('EU Size' 	=> '_eu_women_shoe_size_34_40.tpl', 'Color' => '_Art_202_color_selection.tpl', 'Heel' => '_DN_latin_heels.tpl'),
													'Art 203' 		=> array('EU Size' 	=> '_eu_women_shoe_size_34_40.tpl', 'Color' => '_Art_203_color_selection.tpl', 'Heel' => '_DN_latin_heels.tpl'),
													'Art 204'	 	=> array('EU Size' 	=> '_eu_women_shoe_size_34_40.tpl', 'Color' => '_Art_204_color_selection.tpl', 'Heel' => '_DN_latin_heels.tpl'),
													'Art 205' 		=> array('EU Size' 	=> '_eu_women_shoe_size_34_40.tpl', 'Color' => '_Art_205_color_selection.tpl', 'Heel' => '_DN_latin_heels.tpl'),
													'Art 306 Dafine'=> array('EU Size' 	=> '_eu_women_shoe_size_34_40.tpl', 'Color' => '_Art_306_Dafine_color_selection.tpl', 'Heel' => '_DN_latin_heels.tpl'),
													'Art 406 Perla' => array('EU Size' 	=> '_eu_women_shoe_size_34_40.tpl', 'Color' => '_Art_406_Perla_color_selection.tpl', 'Heel' => '_DN_latin_heels.tpl'),
													'Art 409 Perla' => array('EU Size' 	=> '_eu_women_shoe_size_34_40.tpl', 'Color' => '_Art_409_Perla_color_selection.tpl', 'Heel' => '_DN_latin_heels.tpl'),
													'Art 506 Stella'=> array('EU Size' 	=> '_eu_women_shoe_size_34_40.tpl', 'Color' => '_Art_506_Stella_color_selection.tpl', 'Heel' => '_DN_latin_heels.tpl'),
													'Art 509 Stella'=> array('EU Size' 	=> '_eu_women_shoe_size_34_40.tpl', 'Color' => '_Art_509_Stella_color_selection.tpl', 'Heel' => '_DN_latin_heels.tpl'),
													'Art 883 Venere'=> array('EU Size' 	=> '_eu_women_shoe_size_34_40.tpl', 'Color' => '_Art_883_Venere_color_selection.tpl', 'Heel' => '_DN_gold_heels.tpl'),
													'Art 884 Simple Venere'=> array('EU Size' 	=> '_eu_women_shoe_size_34_40.tpl', 'Color' => '_Art_884_Simple_Venere_color_selection.tpl', 'Heel' => '_DN_latin_heels.tpl'),
													'Art 886 Venere'=> array('EU Size' 	=> '_eu_women_shoe_size_34_40.tpl', 'Color' => '_Art_886_Venere_color_selection.tpl', 'Heel' => '_DN_gold_heels.tpl'),
													'Art 887 Venere'=> array('EU Size' 	=> '_eu_women_shoe_size_34_40.tpl', 'Color' => '_Art_887_Venere_color_selection.tpl', 'Heel' => '_DN_latin_heels.tpl'),
													'Dance Boots Art 007'=> array('EU Size' => '_eu_women_shoe_size_34_40.tpl', 'Color' => '_Dance_Boots_Art_007_color_selection.tpl', 'Heel' => '_DN_gold_high_heels.tpl'),
													'Dance Boots Art 070'=> array('EU Size' => '_eu_women_shoe_size_34_40.tpl', 'Color' => '_Dance_Boots_Art_070_color_selection.tpl'),
													'Mens Bronze Package' => array('Shoes' => '_package_mens_selection.tpl','Shoe size' => '_package_men_shoe_size.tpl', 'Brush' => '_betty_shoe_brush.tpl', 'VE Classic' => '_waist.tpl'),
													'Mens Silver Package' => array('1 shoe' => '_package_mens_selection.tpl', '2 shoe' => '_package_mens_selection_2.tpl', '1 Shoe size' => '_package_men_shoe_size.tpl',  '2 Shoe size' => '_package_men_shoe_size_2.tpl', 'Brush' => '_betty_shoe_brush.tpl', 'VE Classic' => '_waist.tpl'),
	
													);
																
}